import PageIntro from '@/src/Components/design/PageIntro';
import train from '../../../assets/practical training and support.jpg';
import CountSection from '../../../Components/CountSection';
import Link from 'next/link';
const programs = [{"title": "Sustainable Agricultural Practices", "description": "Learn to farm sustainably with nature-based solutions and modern techniques. Our curated curriculum empowers participants to farm smarter, boost yields, earn more, and spend less, while protecting the environment, enhancing farmer safety, and ensuring long-term food security."}, {"title": "Poultry Farming", "description": "Gain practical skills for profitable, sustainable poultry production. Our training program covers brooding, feeding, housing, health management, and marketing. Participants also receive a tool to track feed, medication, productivity, and costs, helping reduce losses, monitor performance, and boost profitability for both new and experienced poultry farmers."}, {"title": "Agribusiness", "description": "Build the skills to launch, manage, and grow a successful agribusiness. Our curated curriculum is tailored to the needs of farmers, entrepreneurs, and agribusiness professionals. The program combines real-world insights, industry-based strategies, and interactive learning to help participants turn agricultural opportunities into profitable and sustainable ventures."}, {"title": "Mentorship/internship", "description": "Bridge the gap between knowledge and real-world experience. Our mentorship and internship program connects young agripreneurs and students with industry experts for hands-on experience, personalized guidance, and career readiness in agribusiness."}, {"title": "Consultancy Services", "description": "EPI combines deep knowledge of Ghana\u2019s agricultural sector with practical industry expertise to deliver trusted consultancy for agricultural initiatives, value-chain development, and credible data to guide your next strategic decision."}];
export default function TrainPage() {
  return <div className="editorial-page">
    <PageIntro eyebrow="Training & Consultancy" title={<>Learn, Grow, and <br /> Build with Us</>} description={<p>We equip farmers and agribusinesses with practical skills, actionable knowledge, and field-tested strategies to build resilient, profitable ventures.</p>} image={train} imageAlt="Practical agricultural training at Eagle Park" action="Register" href="/contact" />
    <section id="programmes" className="editorial-width programme-layout"><div className="section-aside"><h2>What We Offer</h2><p>Tap into our expertise to turn your passion for farming and agribusiness into profitable ventures and lasting impact. We offer training and consultancy services in the following key areas:</p></div><div className="programme-list">{programs.map((program, i) => <details key={program.title} open={i === 0}><summary><h3>{program.title}</h3><i className="ri-add-line" aria-hidden="true" /></summary><div className="programme-detail"><p>{program.description}</p></div></details>)}</div></section>
    <section className="training-approach editorial-width"><h2>Why Choose Us?</h2><div>{[
                            ['Tailored Solutions', 'Services designed around each client’s goals and challenges.'],
                            ['Expert-Led Delivery', 'Training backed by our affiliation with the Ghana TVET Service.'],
                            ['A Partner in Growth, Not Just a Service Provider', 'We build lasting partnerships, not one-off transactions.'],
                            ['Proven Impact', 'More than 9,000 farmers and agripreneurs supported, including women and youth.'],
                        ].map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <CountSection /><section className="page-callout editorial-width"><div><h2>Ready to strengthen your farming or agribusiness skills?</h2><p>Join EPI’s growing community of empowered agripreneurs driving agricultural transformation.</p></div><Link href="/contact" className="primary-link">Get Started <i className="ri-arrow-right-line" aria-hidden="true" /></Link></section>
  </div>;
}
